"""
ClubZap Automated Fixture Sync

Automates uploading, editing, and deleting fixtures on ClubZap dashboard.
Reads diff CSVs generated by clubzap_sync.py and applies them.

Usage:
  py clubzap_automate.py                  -> run full sync (upload + edit + delete)
  py clubzap_automate.py upload           -> upload new fixtures CSV only
  py clubzap_automate.py edit             -> edit changed fixtures only
  py clubzap_automate.py delete           -> delete removed fixtures only

Requires environment variables:
  CLUBZAP_EMAIL    - ClubZap login email
  CLUBZAP_PASSWORD - ClubZap login password
"""

import asyncio
import csv
import os
import sys
import re
import json
from datetime import datetime
from playwright.async_api import async_playwright, TimeoutError as PlaywrightTimeout

from config import (
    CLUBZAP_BASE_URL as BASE_URL, CLUBZAP_FIXTURES_URL as FIXTURES_URL,
    CLUBZAP_RESULTS_URL, CLUBZAP_CLUB_ID, BASELINE_CSV, NEW_CSV, CHANGED_CSV, REMOVED_CSV,
    CLUBZAP_WITHHOLD_SCORES, CLUBZAP_DISABLE_FACEBOOK, CLUBZAP_DISABLE_TWITTER,
)

# Results sync files
NEW_RESULTS_JSON = "new_results_to_sync.json"
RESULTS_BASELINE_JSON = "clubzap_results_baseline.json"


def log(msg):
    timestamp = datetime.now().strftime('%H:%M:%S')
    print(f"[{timestamp}] {msg}")


def read_diff_csv(filepath):
    """Read a diff CSV file into a list of dicts."""
    if not os.path.exists(filepath):
        return []
    with open(filepath, 'r', encoding='utf-8') as f:
        return list(csv.DictReader(f))


class ClubZapAutomation:
    def __init__(self, email, password, headless=True):
        self.email = email
        self.password = password
        self.headless = headless
        self.browser = None
        self.page = None
        self.fixture_map = {}  # fixture_id -> {date, team, opponent, text}
        self._edit_failures = False

    async def start(self):
        """Launch browser and create page."""
        self.playwright = await async_playwright().start()
        self.browser = await self.playwright.chromium.launch(headless=self.headless)
        self.page = await self.browser.new_page()
        self.page.set_default_timeout(30000)
        log("Browser started")

    async def stop(self):
        """Close browser."""
        if self.browser:
            await self.browser.close()
        if self.playwright:
            await self.playwright.stop()
        log("Browser closed")

    async def login(self):
        """Log in to ClubZap dashboard."""
        log("Logging in to ClubZap...")
        await self.page.goto(f"{BASE_URL}/signin", wait_until='domcontentloaded')
        await self.page.wait_for_timeout(3000)

        await self.page.fill('input[type="email"], input[name*="email"]', self.email)
        await self.page.fill('input[type="password"]', self.password)
        await self.page.click('input[type="submit"], button[type="submit"]')
        await self.page.wait_for_timeout(5000)

        if '/signin' in self.page.url:
            raise Exception("Login failed - check credentials")

        log(f"Logged in successfully as {self.email}")

    async def build_fixture_map(self, include_results=False):
        """
        Build a map of all fixtures currently in ClubZap.
        Maps fixture_id -> {date, time, competition, team, opponent, venue}
        
        ClubZap table columns: DATE, TIME, TYPE, COMPETITION, TEAM 1, TEAM 2, VENUE, ACTIONS
        
        If include_results=True, also scans the Results page to find past fixtures.
        """
        log("Building fixture map from ClubZap...")
        self.fixture_map = {}

        page_num = 1
        while True:
            url = f"{FIXTURES_URL}?page={page_num}" if page_num > 1 else FIXTURES_URL
            await self.page.goto(url, wait_until='domcontentloaded')
            await self.page.wait_for_timeout(3000)

            log(f"  Scanning fixtures page {page_num}...")

            rows = await self.page.query_selector_all('table tbody tr')
            if not rows:
                log(f"  No table rows found on page {page_num}")
                break

            rows_on_page = 0
            for row in rows:
                try:
                    # Find the first link with a fixture ID (the date link)
                    link = await row.query_selector('a[href*="/fixtures/"]')
                    if not link:
                        continue
                    href = await link.get_attribute('href') or ''
                    match = re.search(r'/fixtures/(\d+)$', href)
                    if not match:
                        continue
                    fixture_id = match.group(1)

                    # Extract cell text from the row
                    cells = await row.query_selector_all('td')
                    if len(cells) < 7:
                        continue

                    date_text = (await cells[0].inner_text()).strip()
                    time_text = (await cells[1].inner_text()).strip()
                    competition = (await cells[3].inner_text()).strip()
                    team = (await cells[4].inner_text()).strip()
                    opponent = (await cells[5].inner_text()).strip()
                    venue = (await cells[6].inner_text()).strip()

                    self.fixture_map[fixture_id] = {
                        'date': date_text,
                        'time': time_text,
                        'competition': competition,
                        'team': team,
                        'opponent': opponent,
                        'venue': venue,
                    }
                    rows_on_page += 1
                except Exception as e:
                    log(f"    WARNING: Error parsing fixture row: {e}")
                    continue

            log(f"    Found {rows_on_page} fixtures on page {page_num}")

            if rows_on_page == 0:
                break

            # Check for next page link
            next_link = await self.page.query_selector(f'a[href*="page={page_num + 1}"]')
            if next_link:
                page_num += 1
            else:
                break

        fixtures_count = len(self.fixture_map)
        
        # Also scan results page if requested (for past fixtures)
        if include_results:
            log("  Scanning results page for past fixtures...")
            from datetime import datetime
            today = datetime.now()
            
            page_num = 1
            found_future_date = False
            
            while True:
                url = f"{CLUBZAP_RESULTS_URL}?page={page_num}" if page_num > 1 else CLUBZAP_RESULTS_URL
                await self.page.goto(url, wait_until='domcontentloaded')
                await self.page.wait_for_timeout(3000)

                rows = await self.page.query_selector_all('table tbody tr')
                if not rows:
                    break

                rows_on_page = 0
                for row in rows:
                    try:
                        # Results page has links to /results/{id} instead of /fixtures/{id}
                        link = await row.query_selector('a[href*="/results/"]')
                        if not link:
                            continue
                        href = await link.get_attribute('href') or ''
                        match = re.search(r'/results/(\d+)$', href)
                        if not match:
                            continue
                        result_id = match.group(1)

                        # Extract cell text
                        # Results page has different column structure than fixtures:
                        # [0]=checkbox, [1]=competition, [2]=team, [3]=our_score, [4]=opp_score,
                        # [5]=opponent, [6]=date, [7]=time, [8]=venue, [9]=result
                        cells = await row.query_selector_all('td')
                        if len(cells) < 7:
                            continue

                        competition = (await cells[1].inner_text()).strip()
                        team = (await cells[2].inner_text()).strip()
                        opponent = (await cells[5].inner_text()).strip()
                        date_text = (await cells[6].inner_text()).strip()
                        time_text = (await cells[7].inner_text()).strip() if len(cells) > 7 else ""
                        venue = (await cells[8].inner_text()).strip() if len(cells) > 8 else ""
                        
                        # Check if this is a future date (stop scanning if so)
                        try:
                            result_date = datetime.strptime(date_text, '%d/%m/%Y')
                            if result_date > today:
                                log(f"  Reached future date ({date_text}) - stopping results scan")
                                found_future_date = True
                                break
                        except ValueError:
                            pass  # Invalid date format, continue anyway

                        # Store with result_id (not fixture_id, but same structure)
                        self.fixture_map[result_id] = {
                            'date': date_text,
                            'time': time_text,
                            'competition': competition,
                            'team': team,
                            'opponent': opponent,
                            'venue': venue,
                            'is_result': True  # Mark as existing result
                        }
                        rows_on_page += 1
                    except Exception as e:
                        log(f"    WARNING: Error parsing result row: {e}")
                        continue
                
                # Stop if we found a future date
                if found_future_date:
                    break

                if rows_on_page == 0:
                    break

                next_link = await self.page.query_selector(f'a[href*="page={page_num + 1}"]')
                if next_link:
                    page_num += 1
                else:
                    break
            
            results_count = len(self.fixture_map) - fixtures_count
            log(f"  Found {results_count} past results")
            
            # Debug: Log a few recent results to help diagnose matching issues
            if results_count > 0:
                log("  Sample of recent results found:")
                sample_count = 0
                for fixture_id, info in self.fixture_map.items():
                    if info.get('is_result') and sample_count < 5:
                        log(f"    - {info['date']} | {info['team']} vs {info['opponent']}")
                        sample_count += 1

        log(f"  Total: {len(self.fixture_map)} fixtures/results mapped in ClubZap")

    def find_fixture_id(self, date_str, team, opponent):
        """Find a ClubZap fixture ID by matching date, team, and opponent."""
        date_str = date_str.strip()
        team_lower = team.lower().strip()
        opponent_lower = opponent.lower().strip()

        for fixture_id, info in self.fixture_map.items():
            # Match date (ClubZap shows DD/MM/YYYY)
            if info['date'] != date_str:
                continue
            # Match opponent
            if info['opponent'].lower().strip() != opponent_lower:
                continue
            # Match team
            if info['team'].lower().strip() == team_lower:
                return fixture_id

        # Fuzzy fallback: match date + opponent only (may be ambiguous if multiple teams play same opponent on same date)
        for fixture_id, info in self.fixture_map.items():
            if info['date'] == date_str and info['opponent'].lower().strip() == opponent_lower:
                log(f"    NOTE: Fuzzy match used for {date_str} vs {opponent_lower} (matched team: {info['team']})")
                return fixture_id

        return None

    async def upload_new_fixtures(self):
        """Upload new fixtures CSV via ClubZap's file input on the fixtures page."""
        fixtures = read_diff_csv(NEW_CSV)
        if not fixtures:
            log("No new fixtures to upload")
            return 0

        csv_path = os.path.abspath(NEW_CSV)
        log(f"Uploading {len(fixtures)} new fixtures from {NEW_CSV}...")

        await self.page.goto(FIXTURES_URL, wait_until='domcontentloaded')
        await self.page.wait_for_timeout(3000)

        # Count existing fixtures before upload
        rows_before = await self.page.query_selector_all('table tbody tr')
        log(f"  Fixtures before upload: {len(rows_before)}")

        # The upload file input is directly on the fixtures page
        file_input = await self.page.query_selector('input[type="file"]')
        if not file_input:
            log("ERROR: Could not find file input on fixtures page")
            return 0

        await file_input.set_input_files(csv_path)
        log("  CSV file selected")

        # Look for a submit/upload button to click after file selection
        submit_btn = await self.page.query_selector(
            'input[type="submit"][value*="Upload"], input[type="submit"][value*="Import"], '
            'input[type="submit"], button[type="submit"]'
        )
        if submit_btn:
            btn_text = await submit_btn.get_attribute('value') or await submit_btn.inner_text()
            log(f"  Clicking submit button: {btn_text}")
            await submit_btn.click()
            await self.page.wait_for_timeout(8000)
        else:
            log("  No submit button found, waiting for auto-upload...")
            await self.page.wait_for_timeout(8000)

        # Check page for success indicators
        log(f"  Current URL: {self.page.url}")

        # Look for flash/alert messages (specific elements, not page-wide text)
        alerts = await self.page.query_selector_all('.alert, .error, .flash, .notice')
        success_found = False
        for alert in alerts:
            text = (await alert.inner_text()).strip()
            if text:
                log(f"  Alert: {text}")
                if any(w in text.lower() for w in ('success', 'imported', 'uploaded')):
                    success_found = True

        # Count fixtures on current page after upload
        rows_after = await self.page.query_selector_all('table tbody tr')
        log(f"  Fixtures after upload: {len(rows_after)} (was {len(rows_before)} on first page)")

        if len(rows_after) > len(rows_before):
            actual_new = len(rows_after) - len(rows_before)
            if actual_new < len(fixtures):
                log(f"  WARNING: Only {actual_new} of {len(fixtures)} fixtures appeared on page 1 - some may have been rejected")
            else:
                log(f"  Upload appears successful ({actual_new} new on first page)")
            return actual_new

        if success_found:
            log(f"  Flash message indicated success for {len(fixtures)} fixtures")
            return len(fixtures)

        log(f"  WARNING: Upload may have failed - fixture count unchanged ({len(rows_before)} -> {len(rows_after)})")
        return 0

    async def edit_fixture(self, fixture_id, changes):
        """Edit a single fixture by navigating to its edit page."""
        edit_url = f"{BASE_URL}/fixtures/{fixture_id}/edit"
        await self.page.goto(edit_url, wait_until='domcontentloaded')
        await self.page.wait_for_timeout(3000)

        edited = False
        failed_fields = []

        for field, new_value in changes.items():
            try:
                if field == 'Time':
                    # datetime-local input: value format is 2026-09-30T19:00:00
                    time_input = await self.page.query_selector(
                        '#fixture_event_attributes_start, input[name*="[start]"]'
                    )
                    if time_input:
                        current_val = await time_input.get_attribute('value') or ''
                        # Replace time portion: keep date (YYYY-MM-DD), replace T and after
                        if 'T' in current_val:
                            date_part = current_val.split('T')[0]
                            # new_value is like "19:30" from CSV
                            # datetime-local fill() requires YYYY-MM-DDTHH:mm (no seconds)
                            new_dt = f"{date_part}T{new_value}"
                            await time_input.evaluate('el => el.value = ""')
                            await time_input.fill(new_dt)
                            log(f"    Time: {current_val} -> {new_dt}")
                            edited = True

                elif field == 'Venue':
                    venue_input = await self.page.query_selector(
                        '#fixture_event_attributes_venue, input[name*="[venue]"]'
                    )
                    if venue_input:
                        await venue_input.fill('')
                        await venue_input.fill(new_value)
                        edited = True

                elif field == 'Ground':
                    # Select values are lowercase: home, away, neutral
                    ground_select = await self.page.query_selector(
                        '#fixture_event_attributes_ground_type, select[name*="[ground_type]"]'
                    )
                    if ground_select:
                        val = new_value.lower().strip()
                        await ground_select.select_option(value=val)
                        edited = True

                elif field == 'Referee':
                    ref_input = await self.page.query_selector(
                        '#fixture_event_attributes_referee, input[name*="[referee]"]'
                    )
                    if ref_input:
                        await ref_input.fill('')
                        await ref_input.fill(new_value)
                        edited = True

            except Exception as e:
                log(f"    WARNING: Could not update {field}: {e}")
                failed_fields.append(field)

        if edited:
            submit_btn = await self.page.query_selector(
                'input[type="submit"], button[type="submit"], input[name="commit"]'
            )
            if submit_btn:
                await submit_btn.click()
                await self.page.wait_for_timeout(3000)

                # Check for success
                if '/edit' not in self.page.url:
                    return True, len(failed_fields) > 0
                content = await self.page.content()
                if 'success' in content.lower() or 'updated' in content.lower():
                    return True, len(failed_fields) > 0

        return False, len(failed_fields) > 0

    async def edit_changed_fixtures(self):
        """Edit all changed fixtures."""
        changed = read_diff_csv(CHANGED_CSV)
        if not changed:
            log("No changed fixtures to edit")
            return 0

        log(f"Editing {len(changed)} changed fixtures...")
        edited_count = 0

        for row in changed:
            date = row.get('Date', '')
            team = row.get('Team', '')
            opponent = row.get('Opponent', '')
            changes_desc = row.get('Changes', '')

            fixture_id = self.find_fixture_id(date, team, opponent)
            if not fixture_id:
                log(f"  SKIP: Could not find {date} {team} vs {opponent} in ClubZap")
                continue

            # Parse changes: "Time: '14:30' -> '13:00'; Venue: 'X' -> 'Y'"
            changes = {}
            if changes_desc:
                for change in changes_desc.split('; '):
                    if '->' in change and ':' in change:
                        field = change.split(':')[0].strip()
                        new_val = change.split('->')[-1].strip().strip("'")
                        changes[field] = new_val

            if not changes:
                for col in ['Time', 'Venue', 'Ground', 'Referee']:
                    if row.get(col, '').strip():
                        changes[col] = row[col].strip()

            log(f"  Editing: {date} {team} vs {opponent} (ID: {fixture_id})")
            for f, v in changes.items():
                log(f"    {f} -> {v}")

            success, had_failures = await self.edit_fixture(fixture_id, changes)
            if success:
                if had_failures:
                    log(f"    Partially saved (some fields failed)")
                else:
                    log(f"    Saved")
                edited_count += 1
            else:
                log(f"    WARNING: Edit may not have saved")
            if had_failures:
                self._edit_failures = True

        return edited_count

    async def delete_fixture_by_id(self, fixture_id):
        """Delete a fixture using the Delete link on the fixtures list page."""
        # Navigate to the fixture view page
        view_url = f"{BASE_URL}/fixtures/{fixture_id}"
        await self.page.goto(view_url, wait_until='domcontentloaded')
        await self.page.wait_for_timeout(2000)

        # Handle the confirmation dialog that appears on delete
        self.page.once('dialog', lambda dialog: asyncio.ensure_future(dialog.accept()))

        # Click the Delete button/link
        delete_btn = await self.page.query_selector(
            'a:has-text("Delete"), input[value="Delete"]'
        )

        if not delete_btn:
            return False

        await delete_btn.click()
        await self.page.wait_for_timeout(3000)

        # Success if redirected away from the fixture page
        if f'/fixtures/{fixture_id}' not in self.page.url:
            return True
        return False

    async def delete_removed_fixtures(self):
        """Delete all removed and postponed fixtures."""
        removed = read_diff_csv(REMOVED_CSV)
        if not removed:
            log("No removed fixtures to delete")
            return 0

        log(f"Deleting {len(removed)} removed/postponed fixtures...")
        deleted_count = 0

        for row in removed:
            date = row.get('Date', '')
            team = row.get('Team', '')
            opponent = row.get('Opponent', '')

            fixture_id = self.find_fixture_id(date, team, opponent)
            if not fixture_id:
                log(f"  SKIP: Could not find {date} {team} vs {opponent} in ClubZap")
                continue

            log(f"  Deleting: {date} {team} vs {opponent} (ID: {fixture_id})")
            success = await self.delete_fixture_by_id(fixture_id)
            if success:
                log(f"    Deleted")
                deleted_count += 1
            else:
                log(f"    WARNING: Delete may have failed")

        return deleted_count

    async def find_fixture_for_result(self, result):
        """Find the ClubZap fixture/result ID that corresponds to this result."""
        date_str = result['date']
        team = result['team']
        opponent = result['opponent']
        
        log(f"    Searching for: date='{date_str}', team='{team}', opponent='{opponent}'")
        
        fixture_id = self.find_fixture_id(date_str, team, opponent)
        if fixture_id:
            fixture_info = self.fixture_map.get(fixture_id, {})
            is_existing_result = fixture_info.get('is_result', False)
            if is_existing_result:
                log(f"    ✓ Found existing result ID {fixture_id}")
            else:
                log(f"    ✓ Found fixture ID {fixture_id}")
            return fixture_id, is_existing_result
        else:
            log(f"    ✗ No match found in {len(self.fixture_map)} fixtures/results")
            # Debug: Show matches by date only
            date_matches = [f for f, info in self.fixture_map.items() if info['date'] == date_str]
            if date_matches:
                log(f"    Found {len(date_matches)} fixtures/results on {date_str}:")
                for fid in date_matches[:5]:
                    info = self.fixture_map[fid]
                    log(f"      - {info['team']} vs {info['opponent']}")
            else:
                log(f"    No fixtures/results found on {date_str} in ClubZap")
                log(f"    This fixture was never added to ClubZap")
            return None, False

    async def enter_result_for_fixture(self, fixture_id, result):
        """Enter a result for a specific fixture in ClubZap."""
        log(f"      🎯 Entering result for fixture ID: {fixture_id}")
        log(f"      📊 Result: {result['home_team']} {result['home_score']} v {result['away_score']} {result['away_team']}")
        
        # Navigate to the fixture page to look for result entry option
        fixture_url = f"{BASE_URL}/fixtures/{fixture_id}"
        log(f"      🌐 Navigating to: {fixture_url}")
        await self.page.goto(fixture_url, wait_until='domcontentloaded')
        await self.page.wait_for_timeout(2000)
        
        # Look for "Add Result" or "Enter Result" button/link
        result_btn = await self.page.query_selector(
            'a:has-text("Add Result"), a:has-text("Enter Result"), '
            'button:has-text("Add Result"), button:has-text("Enter Result"), '
            'a[href*="/result"], a[href*="/score"]'
        )
        
        if not result_btn:
            # Try alternative patterns
            result_btn = await self.page.query_selector(
                'a:has-text("Result"), button:has-text("Result")'
            )
        
        if not result_btn:
            log(f"      No result entry button found for fixture {fixture_id}")
            return False
        
        # Click the result entry button
        await result_btn.click()
        await self.page.wait_for_timeout(3000)
        
        # Now we should be on the result entry form
        # The form structure will depend on ClubZap's implementation
        # Common patterns for GAA results:
        
        try:
            # Try to find score input fields
            # Pattern 1: Separate goals and points fields
            home_goals = await self.page.query_selector(
                'input[name*="home"][name*="goal"], input[id*="home"][id*="goal"]'
            )
            home_points = await self.page.query_selector(
                'input[name*="home"][name*="point"], input[id*="home"][id*="point"]'
            )
            away_goals = await self.page.query_selector(
                'input[name*="away"][name*="goal"], input[id*="away"][id*="goal"]'
            )
            away_points = await self.page.query_selector(
                'input[name*="away"][name*="point"], input[id*="away"][id*="point"]'
            )
            
            if home_goals and home_points and away_goals and away_points:
                # Parse GAA scores (e.g., "1-6" -> 1 goal, 6 points)
                home_score_parts = result['home_score'].split('-')
                away_score_parts = result['away_score'].split('-')
                
                await home_goals.fill(home_score_parts[0])
                await home_points.fill(home_score_parts[1])
                await away_goals.fill(away_score_parts[0])
                await away_points.fill(away_score_parts[1])
                
                log(f"      Entered scores: Home {result['home_score']}, Away {result['away_score']}")
            else:
                # Pattern 2: Single score fields (might accept "1-6" format)
                home_score_field = await self.page.query_selector(
                    'input[name*="home"][name*="score"], input[id*="home"][id*="score"]'
                )
                away_score_field = await self.page.query_selector(
                    'input[name*="away"][name*="score"], input[id*="away"][id*="score"]'
                )
                
                if home_score_field and away_score_field:
                    await home_score_field.fill(result['home_score'])
                    await away_score_field.fill(result['away_score'])
                    log(f"      Entered scores: Home {result['home_score']}, Away {result['away_score']}")
                else:
                    log(f"      Could not find score input fields")
                    return False
            
            # Look for additional fields that might be available
            # Referee field
            referee_field = await self.page.query_selector(
                'input[name*="referee"], input[id*="referee"]'
            )
            if referee_field and result.get('referee'):
                await referee_field.fill(result['referee'])
            
            # Handle result publishing options
            await self._configure_result_publishing_options()
            
            # Submit the result
            submit_btn = await self.page.query_selector(
                'input[type="submit"], button[type="submit"], '
                'input[value*="Save"], button:has-text("Save")'
            )
            
            if submit_btn:
                await submit_btn.click()
                await self.page.wait_for_timeout(3000)
                
                # Check for success indicators
                if '/fixtures/' in self.page.url and f'/{fixture_id}' not in self.page.url:
                    # Redirected away from the form, likely success
                    return True
                
                # Look for success messages
                success_indicators = await self.page.query_selector_all(
                    '.alert-success, .success, .flash-success'
                )
                for indicator in success_indicators:
                    text = await indicator.inner_text()
                    if 'success' in text.lower() or 'saved' in text.lower():
                        return True
                
                # If still on the form page, check for errors
                error_indicators = await self.page.query_selector_all(
                    '.alert-error, .error, .flash-error'
                )
                if error_indicators:
                    for error in error_indicators:
                        error_text = await error.inner_text()
                        log(f"      Error: {error_text}")
                    return False
                
                return True  # Assume success if no errors found
            else:
                log(f"      Could not find submit button")
                return False
                
        except Exception as e:
            log(f"      Error entering result: {e}")
            return False

    async def _configure_result_publishing_options(self):
        """Configure result publishing options based on config settings."""
        try:
            # Option 1: "Withhold Scores from Application, Website & Social"
            # This makes the result show only as Win/Loss/Draw without actual scores
            if CLUBZAP_WITHHOLD_SCORES:
                withhold_checkbox = await self.page.query_selector(
                    'input[type="checkbox"][name*="withhold"], '
                    'input[type="checkbox"][name*="hide"], '
                    'input[type="checkbox"][id*="withhold"], '
                    'input[type="checkbox"][id*="hide"]'
                )
                
                if not withhold_checkbox:
                    # Try alternative patterns for withholding scores
                    withhold_checkbox = await self.page.query_selector(
                        'input[type="checkbox"]:near(:text("Withhold")), '
                        'input[type="checkbox"]:near(:text("Hide")), '
                        'input[type="checkbox"]:near(:text("Win, Loss or Draw"))'
                    )
                
                if withhold_checkbox:
                    # Check if it's already checked
                    is_checked = await withhold_checkbox.is_checked()
                    if not is_checked:
                        await withhold_checkbox.check()
                        log(f"      ✓ Enabled 'Withhold Scores' - result will show as Win/Loss/Draw only")
                    else:
                        log(f"      ✓ 'Withhold Scores' already enabled")
                else:
                    log(f"      Could not find 'Withhold Scores' checkbox")
            else:
                log(f"      Withhold scores disabled in config")
            
            # Option 2: Disable Facebook publishing
            if CLUBZAP_DISABLE_FACEBOOK:
                facebook_checkbox = await self.page.query_selector(
                    'input[type="checkbox"][name*="facebook"], '
                    'input[type="checkbox"][id*="facebook"]'
                )
                
                if not facebook_checkbox:
                    # Try alternative patterns
                    facebook_checkbox = await self.page.query_selector(
                        'input[type="checkbox"]:near(:text("Facebook")), '
                        'input[type="checkbox"]:near(:text("FB"))'
                    )
                
                if facebook_checkbox:
                    is_checked = await facebook_checkbox.is_checked()
                    if is_checked:
                        await facebook_checkbox.uncheck()
                        log(f"      ✓ Disabled Facebook publishing")
                    else:
                        log(f"      ✓ Facebook publishing already disabled")
                else:
                    log(f"      Could not find Facebook checkbox")
            else:
                log(f"      Facebook publishing enabled in config")
            
            # Option 3: Disable Twitter publishing
            if CLUBZAP_DISABLE_TWITTER:
                twitter_checkbox = await self.page.query_selector(
                    'input[type="checkbox"][name*="twitter"], '
                    'input[type="checkbox"][id*="twitter"]'
                )
                
                if not twitter_checkbox:
                    # Try alternative patterns
                    twitter_checkbox = await self.page.query_selector(
                        'input[type="checkbox"]:near(:text("Twitter")), '
                        'input[type="checkbox"]:near(:text("X"))'
                    )
                
                if twitter_checkbox:
                    is_checked = await twitter_checkbox.is_checked()
                    if is_checked:
                        await twitter_checkbox.uncheck()
                        log(f"      ✓ Disabled Twitter publishing")
                    else:
                        log(f"      ✓ Twitter publishing already disabled")
                else:
                    log(f"      Could not find Twitter checkbox")
            else:
                log(f"      Twitter publishing enabled in config")
            
        except Exception as e:
            log(f"      Warning: Error configuring publishing options: {e}")
            # Don't fail the entire result entry if publishing options fail

    async def create_brand_new_result(self, result):
        """Create a brand new result in ClubZap (without pre-existing fixture)."""
        log(f"      🆕 Creating brand new result")
        log(f"      📊 Result: {result['date']} - {result['team']} {result['our_score']} v {result['opponent_score']} {result['opponent']}")
        
        # Navigate to the brand new result page
        brand_new_url = f"{BASE_URL}/clubs/{CLUBZAP_CLUB_ID}/results/brand_new"
        log(f"      🌐 Navigating to: {brand_new_url}")
        await self.page.goto(brand_new_url, wait_until='domcontentloaded')
        await self.page.wait_for_timeout(3000)
        
        try:
            # Debug: Check what page we're actually on
            current_url = self.page.url
            log(f"      DEBUG: Current URL after navigation: {current_url}")
            
            # Debug: Get page title
            page_title = await self.page.title()
            log(f"      DEBUG: Page title: {page_title}")
            
            # Debug: Check for error messages or redirects
            body_text = await self.page.evaluate('() => document.body.innerText')
            if 'error' in body_text.lower() or 'permission' in body_text.lower() or 'access denied' in body_text.lower():
                log(f"      DEBUG: Page contains error/permission text: {body_text[:200]}")
            
            # Debug: Log all input fields on the page
            all_inputs = await self.page.query_selector_all('input, select, textarea')
            log(f"      DEBUG: Found {len(all_inputs)} form fields on brand_new page")
            for i, inp in enumerate(all_inputs[:15]):  # Log first 15 fields
                tag = await inp.evaluate('el => el.tagName')
                name = await inp.get_attribute('name') or ''
                id_attr = await inp.get_attribute('id') or ''
                type_attr = await inp.get_attribute('type') or ''
                placeholder = await inp.get_attribute('placeholder') or ''
                log(f"        [{i}] {tag} name='{name}' id='{id_attr}' type='{type_attr}' placeholder='{placeholder}'")
            
            # Fill in the result form
            # Date/time field (datetime-local format: YYYY-MM-DDTHH:MM)
            # Convert DD/MM/YYYY to YYYY-MM-DD
            from datetime import datetime
            try:
                date_obj = datetime.strptime(result['date'], '%d/%m/%Y')
                datetime_value = date_obj.strftime('%Y-%m-%dT19:30')  # Default to 7:30 PM
            except ValueError:
                datetime_value = result['date']  # Fallback to original
            
            date_field = await self.page.query_selector(
                'input[name="result[event_attributes][start]"]'
            )
            if date_field:
                await date_field.fill(datetime_value)
                log(f"      ✓ Entered date: {datetime_value}")
            
            # Event type selection (dropdown) - required field
            # Options: League, Championship / Cup, Friendly
            event_type_field = await self.page.query_selector(
                'select[name="result[event_attributes][event_type]"]'
            )
            if event_type_field:
                # Default to "League" for most matches
                try:
                    await event_type_field.select_option(label='League')
                    await self.page.wait_for_timeout(500)  # Wait for selection to register
                    log(f"      ✓ Selected event type: League")
                except Exception as e:
                    log(f"      ⚠️  Could not select 'League' event type: {e}")
                    # Try selecting by index (1 = League, 2 = Championship/Cup, 3 = Friendly)
                    try:
                        await event_type_field.select_option(index=1)
                        await self.page.wait_for_timeout(500)
                        log(f"      ✓ Selected event type by index")
                    except:
                        log(f"      ❌ Failed to select event type")
            
            # Team selection (dropdown)
            team_field = await self.page.query_selector(
                'select[name="result[event_attributes][team_id]"]'
            )
            if team_field:
                await team_field.select_option(label=result['team'])
                await self.page.wait_for_timeout(500)  # Wait for selection to register
                log(f"      ✓ Selected team: {result['team']}")
            
            # Competition name (text field) - required
            competition_field = await self.page.query_selector(
                'input[name="result[event_attributes][competition_name]"]'
            )
            if competition_field:
                # Use competition from result if available, otherwise use a default
                competition_name = result.get('competition', 'League Match')
                await competition_field.fill(competition_name)
                await self.page.wait_for_timeout(500)  # Wait for input to register
                log(f"      ✓ Entered competition: {competition_name}")
            
            # Opponent field
            opponent_field = await self.page.query_selector(
                'input[name="result[event_attributes][opponent]"]'
            )
            if opponent_field:
                await opponent_field.fill(result['opponent'])
                log(f"      ✓ Entered opponent: {result['opponent']}")
            
            # Score fields - ClubZap uses single score fields (e.g., "1-6" format)
            own_score_field = await self.page.query_selector(
                'input[name="result[own_score]"]'
            )
            opponent_score_field = await self.page.query_selector(
                'input[name="result[opponent_score]"]'
            )
            
            if own_score_field and opponent_score_field:
                # Clear fields first
                await own_score_field.fill('')
                await opponent_score_field.fill('')
                
                # Fill with scores
                await own_score_field.fill(result['our_score'])
                await own_score_field.press('Tab')  # Trigger change event
                await self.page.wait_for_timeout(300)
                
                await opponent_score_field.fill(result['opponent_score'])
                await opponent_score_field.press('Tab')  # Trigger change event
                await self.page.wait_for_timeout(300)
                
                log(f"      ✓ Entered scores: {result['our_score']} v {result['opponent_score']}")
            else:
                log(f"      ⚠️  Could not find score input fields")
                return False
            
            # Handle result publishing options
            await self._configure_result_publishing_options()
            
            # DEBUG: Verify all fields are filled before submitting
            log(f"      DEBUG: Verifying form fields before submit...")
            event_type_value = await event_type_field.evaluate('el => el.value') if event_type_field else None
            team_value = await team_field.evaluate('el => el.value') if team_field else None
            competition_value = await competition_field.evaluate('el => el.value') if competition_field else None
            opponent_value = await opponent_field.evaluate('el => el.value') if opponent_field else None
            own_score_value = await own_score_field.evaluate('el => el.value') if own_score_field else None
            opp_score_value = await opponent_score_field.evaluate('el => el.value') if opponent_score_field else None
            
            log(f"        Event type: '{event_type_value}'")
            log(f"        Team: '{team_value}'")
            log(f"        Competition: '{competition_value}'")
            log(f"        Opponent: '{opponent_value}'")
            log(f"        Own score: '{own_score_value}'")
            log(f"        Opp score: '{opp_score_value}'")
            
            # Submit the result
            submit_btn = await self.page.query_selector(
                'input[type="submit"], button[type="submit"], '
                'input[value*="Save"], button:has-text("Save"), button:has-text("Create")'
            )
            
            if submit_btn:
                log(f"      🔘 Clicking submit button...")
                await submit_btn.click()
                await self.page.wait_for_timeout(3000)
                
                # Debug: Check what happened after submit
                final_url = self.page.url
                log(f"      DEBUG: URL after submit: {final_url}")
                
                # Check for success - redirect to result detail page
                if '/results/' in final_url and '/brand_new' not in final_url:
                    log(f"      ✓ Redirected to result page - success!")
                    return True
                
                # Still on brand_new page - check for messages
                if '/brand_new' in final_url:
                    log(f"      ⚠️  Still on brand_new page - checking for errors...")
                    
                    # Get all visible text to see what's on the page
                    body_text = await self.page.evaluate('() => document.body.innerText')
                    
                    # Check for validation errors
                    if 'error' in body_text.lower() or 'required' in body_text.lower() or 'invalid' in body_text.lower():
                        log(f"      ❌ Form validation errors detected:")
                        # Look for specific error messages
                        error_elements = await self.page.query_selector_all('.error, .invalid-feedback, .field_with_errors')
                        for elem in error_elements[:5]:
                            error_text = await elem.inner_text()
                            if error_text.strip():
                                log(f"        - {error_text.strip()}")
                        return False
                
                # Look for success messages
                success_indicators = await self.page.query_selector_all(
                    '.alert-success, .success, .flash-success, .notice'
                )
                for indicator in success_indicators:
                    text = await indicator.inner_text()
                    if text.strip() and ('success' in text.lower() or 'saved' in text.lower() or 'created' in text.lower()):
                        log(f"      ✓ Success message: {text.strip()}")
                        return True
                
                # Check for errors
                error_indicators = await self.page.query_selector_all(
                    '.alert-error, .error, .flash-error, .alert-danger, .alert'
                )
                if error_indicators:
                    for error in error_indicators:
                        error_text = await error.inner_text()
                        if error_text.strip():
                            log(f"      ❌ Error: {error_text.strip()}")
                    
                    # Get the entire page text to see all validation messages
                    log(f"      DEBUG: Searching for validation errors in page content...")
                    page_content = await self.page.content()
                    
                    # Look for common error patterns in the HTML
                    if 'Event type' in page_content and ('required' in page_content or "can't be blank" in page_content):
                        log(f"        - Event type is required")
                    if 'Competition' in page_content and ('required' in page_content or "can't be blank" in page_content):
                        log(f"        - Competition is required")
                    
                    # Also check for field-specific errors (often shown near inputs)
                    field_errors = await self.page.query_selector_all('.field_with_errors, .invalid-feedback, .help-block.error, .text-danger, li')
                    if field_errors:
                        log(f"      Field validation errors found:")
                        for field_error in field_errors[:10]:
                            error_text = await field_error.inner_text()
                            if error_text.strip() and len(error_text.strip()) < 100:  # Avoid huge blocks
                                log(f"        - {error_text.strip()}")
                    
                    return False
                
                log(f"      ⚠️  No clear success/error indicator - assuming failure")
                return False
            else:
                log(f"      ⚠️  Could not find submit button")
                return False
                
        except Exception as e:
            log(f"      ❌ Error creating brand new result: {e}")
            return False

    async def sync_results(self, test_mode=False):
        """Sync new results to ClubZap."""
        results_file = "test_single_result.json" if test_mode else NEW_RESULTS_JSON
        
        if not os.path.exists(results_file):
            log(f"No results file found: {results_file}")
            return 0
        
        # Load new results
        try:
            with open(results_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                new_results = data.get('results', [])
        except Exception as e:
            log(f"Error loading results from {results_file}: {e}")
            return 0
        
        if not new_results:
            log("No new results to sync")
            return 0
        
        log(f"Syncing {len(new_results)} new results to ClubZap...")
        
        # Build fixture map including results page (for past fixtures)
        await self.build_fixture_map(include_results=True)
        
        synced_count = 0
        failed_results = []
        
        for result in new_results:
            date = result['date']
            team = result['team']
            opponent = result['opponent']
            our_score = result['our_score']
            opponent_score = result['opponent_score']
            
            log(f"  Processing: {date} {team} {our_score} v {opponent_score} {opponent}")
            
            # Find corresponding fixture/result
            fixture_id, is_existing_result = await self.find_fixture_for_result(result)
            
            if is_existing_result:
                log(f"    ⚠️  Result already exists - skipping (ID: {fixture_id})")
                synced_count += 1  # Count as synced since it already exists
                continue
            
            # Enter the result (either for existing fixture or create brand new)
            if fixture_id:
                success = await self.enter_result_for_fixture(fixture_id, result)
            else:
                log(f"    No fixture found - creating brand new result")
                success = await self.create_brand_new_result(result)
            
            if success:
                log(f"    ✓ Result entered successfully")
                synced_count += 1
            else:
                log(f"    ✗ Failed to enter result")
                failed_results.append(result)
        
        log(f"Results sync complete: {synced_count} synced, {len(failed_results)} failed")
        
        if failed_results:
            log("Failed results:")
            for result in failed_results:
                log(f"  - {result['date']} {result['team']} vs {result['opponent']}")
        
        return synced_count

    async def sync(self, actions=None):
        """Run full sync: upload new fixtures, edit changed fixtures, delete removed fixtures, sync results."""
        if actions is None:
            actions = ['upload', 'edit', 'delete', 'results']

        self._edit_failures = False  # reset for this run

        try:
            await self.start()
            await self.login()

            results = {}

            if 'upload' in actions and os.path.exists(NEW_CSV):
                results['uploaded'] = await self.upload_new_fixtures()

            if ('edit' in actions or 'delete' in actions or 'results' in actions or 'test' in actions):
                if os.path.exists(CHANGED_CSV) or os.path.exists(REMOVED_CSV) or os.path.exists(NEW_RESULTS_JSON):
                    await self.build_fixture_map()

            if 'edit' in actions and os.path.exists(CHANGED_CSV):
                results['edited'] = await self.edit_changed_fixtures()

            if 'delete' in actions and os.path.exists(REMOVED_CSV):
                results['deleted'] = await self.delete_removed_fixtures()

            if ('results' in actions or 'test' in actions) and os.path.exists(NEW_RESULTS_JSON):
                test_mode = 'test' in actions
                results['results_synced'] = await self.sync_results(test_mode=test_mode)

            log("=" * 50)
            log("  ClubZap Sync Complete")
            log("=" * 50)
            if 'uploaded' in results:
                log(f"  Uploaded:      {results['uploaded']} new fixtures")
            if 'edited' in results:
                log(f"  Edited:        {results['edited']} fixtures")
            if 'deleted' in results:
                log(f"  Deleted:       {results['deleted']} fixtures")
            if 'results_synced' in results:
                log(f"  Results synced: {results['results_synced']} results")
            log("=" * 50)

            if any(v > 0 for v in results.values()):
                if getattr(self, '_edit_failures', False):
                    log("WARNING: Some edits failed - skipping baseline update")
                    log("  Next run will retry the failed edits")
                else:
                    try:
                        from clubzap_sync import mark_uploaded
                        log("Updating fixtures baseline...")
                        mark_uploaded()
                        
                        # Update results baseline if results were synced
                        if results.get('results_synced', 0) > 0:
                            from results_sync import mark_synced
                            log("Updating results baseline...")
                            mark_synced()
                    except Exception as e:
                        log(f"WARNING: Could not update baseline: {e}")

            return results

        except Exception as e:
            log(f"ERROR: {e}")
            raise
        finally:
            await self.stop()


async def main():
    email = os.environ.get('CLUBZAP_EMAIL', '')
    password = os.environ.get('CLUBZAP_PASSWORD', '')

    if not email or not password:
        log("No ClubZap credentials found - skipping automation")
        log("  Set CLUBZAP_EMAIL and CLUBZAP_PASSWORD to enable")
        sys.exit(0)

    # Check if there are any diff files to process
    has_work = any(os.path.exists(f) for f in [NEW_CSV, CHANGED_CSV, REMOVED_CSV, NEW_RESULTS_JSON])
    if not has_work:
        log("No diff files found - nothing to sync to ClubZap")
        sys.exit(0)

    # First-run protection: skip bulk upload if no baseline exists
    # This prevents uploading ALL fixtures when the baseline hasn't been established
    if os.path.exists(NEW_CSV) and not os.path.exists(BASELINE_CSV):
        with open(NEW_CSV, 'r') as f:
            count = sum(1 for _ in csv.DictReader(f))
        if count > 20:
            log(f"SAFETY: First run detected (no baseline) with {count} new fixtures")
            log("  Skipping bulk upload to prevent duplicates.")
            log("  Run 'py clubzap_sync.py uploaded' to establish baseline first.")
            sys.exit(0)

    actions = None
    if len(sys.argv) > 1:
        action = sys.argv[1].lower()
        if action in ('upload', 'edit', 'delete', 'results', 'test'):
            actions = [action]
        elif action == 'all':
            actions = None
        else:
            print(f"Unknown action: {action}")
            print("Usage: py clubzap_automate.py [upload|edit|delete|results|test|all]")
            sys.exit(1)

    headless = os.environ.get('CLUBZAP_HEADLESS', 'true').lower() != 'false'

    automation = ClubZapAutomation(email, password, headless=headless)
    await automation.sync(actions)


if __name__ == '__main__':
    asyncio.run(main())
